### ISSUE TITLE
Failing to launch ER from mod engine

### ISSUE THREAD

**Issue by 2beyajay** [soulsmods/ModEngine2#100]
When trying to launch ER using .bat an error message pops up saying "the code execution cannot proceed because CONCRT140.dll was not found. Reinstalling the program may fix the problem.

Not sure what this is about. The game runs using steam.

**Comment by Van-Rock** [comment]
Вам нужно переустановить библиотеку MicrosoftVisualC, скорее всего года 2015-2019, скачайте с официального сайта. https://learn.microsoft.com/ru-ru/cpp/windows/latest-supported-vc-redist?view=msvc-170
