### ISSUE TITLE
Armored Core 6 Steam Deck/Linux

### ISSUE THREAD

**Issue by sevenpastzeero** [soulsmods/ModEngine2#140]
Hello,

I am trying to setup modengine2 to work with Armored Core 6 on the steam deck, to use text size mod.
For some reason this mod works, it uses  'regulation.bin' https://www.nexusmods.com/armoredcore6firesofrubicon/mods/25
But these two doesn't : https://www.nexusmods.com/armoredcore6firesofrubicon/mods/26?tab=description
https://www.nexusmods.com/armoredcore6firesofrubicon/mods/35
Any fix or insight on this issue?
All mods are installed in the 'mod' folder.

**Comment by barbatroros** [comment]
I have the same issue but I am using a PC and a pirated copy of AC6.

**Comment by sevenpastzeero** [comment]
Ok, Cloudef updated his fork of Mod Engine 2 for proton/Steam Deck and it is working now.
https://github.com/Cloudef/ModEngine2/issues/19
