### ISSUE TITLE
Modengine 2, which brings up the cmd that closes automatically approx 100 milliseconds after launching it.

### ISSUE THREAD

**Issue by yura5409** [soulsmods/ModEngine2#178]
I have a problem similar to some of the issue i saw, but here's what I have:

 for the past few hours, I've been trying to find solutions to my problem, but nothing (via Steam)
To be honest, I'm completely lost with all the answers I've read

If someone can help, I'm desperate.

Issue:
![Capture d’écran 2024-03-05 064730](https://github.com/soulsmods/ModEngine2/assets/162262679/b153faaa-2c69-4b3c-911c-ce427bddfdec)

Game file Location : "C:\steam\steamapps\common\ELDEN RING\Game"
![Capture d’écran 2024-03-05 065640](https://github.com/soulsmods/ModEngine2/assets/162262679/cb44882e-e449-4387-ba2b-c0aa06c927e5)

"modengine2" Location : "C:\Users\yura\OneDrive\Рабочий стол\ModEngine-2.1.0.0-win64"
        Рабочий стол = (Dekstop) in RU      

![Capture d’écran 2024-03-05 065857](https://github.com/soulsmods/ModEngine2/assets/162262679/ac1b4ef3-2392-4387-a791-21134720fc5f)

how my "config_eldenring" look like : 

mods = [
    { enabled = true, name = "default", path = "mod" }
]

**Comment by HardTekkfreak** [comment]
Move all the content in the same folder with ME2 launcher to the game's directory, change ME2 launcher's name to "start_protected_game.exe" (backup the original one), set it to launch as admin and run it.

**Comment by yura5409** [comment]
> Move all the content in the same folder with ME2 launcher to the game's directory, change ME2 launcher's name to "start_protected_game.exe" (backup the original one), set it to launch as admin and run it.

"I'm sorry, but if I understand correctly, I should take the first folder ("ModEngine-2.1.0.0-win64")
 to put it where the game files are located in ("C:\steam\steamapps\common\ELDEN RING\Game")? If not, I'm not sure which launcher you're referring to specifically. Excuse me."

**Comment by HardTekkfreak** [comment]
Just place all the ME2 folder’s contents inside of the game’s directory (…ELDEN RING\Game) and rename the modengine2_launcher to “start_protected_game.exe”
I had the same exact issue as yours, we even share the devices language.

**Comment by yura5409** [comment]
> Just place all the ME2 folder’s contents inside of the game’s directory (…ELDEN RING\Game) and rename the modengine2_launcher to “start_protected_game.exe”
> I had the same exact issue as yours, we even share the devices language.

omg tysm for your help that ' s finnaly working 💯 Thank you for being able to spare some of your time.
