### ISSUE TITLE
Allow us to set game path please

### ISSUE THREAD

**Issue by Tanksy** [soulsmods/ModEngine2#197]
It's really dumb that you've hardcoded a path to search for when many, many people have their games NOT on the C drive or wherever it is you're searching internally.

**Comment by Gerome100** [comment]
what about -p or --game-path?

you can run modengine2_launcher.exe" -h to get the following informations:

Options:
  -h,--help                   Print this help message and exit
  -t,--launch-target ENUM:value in {ac6->3,ds3->1,er->2} OR {3,1,2}
                              Launch target
  -p,--game-path TEXT:FILE    Path to game executable. Will autodetect if not specified.
  -c,--config TEXT:FILE       ModEngine configuration file path
  -s,--suspend BOOLEAN        Start the game in a suspended state
  --modengine-dll TEXT        ModEngine DLL file path (modengine2.dll)

**Comment by Crunchsnifflet** [comment]
I second this. I can't get the damned thing to work, no matter how many times I edit the bin file

**Comment by Menno5** [comment]
I second this too. No matter what I do, nothing happens other then a windows opens and closes in a fraction of a second.

**Comment by Obesemicrowave** [comment]
yea me too menno5, ive tried to edit the batch file with game path and ive renamed the launcher to start_protected_game.exe but still, launches for fraction of a second and then nothing

**Comment by dmantisk** [comment]
It worked for me

Edit your launchmod_eldenring.bat with a text editor(notepad) so its content looks like the following

.\modengine2_launcher.exe -t er -c .\config_eldenring.toml -p "D:\path\to\game\eldenring.exe"

Obviously, you have to use the correct path to where it's installed in your PC

**Comment by premiumghoul** [comment]
> It worked for me
> 
> Edit your launchmod_eldenring.bat with a text editor(notepad) so its content looks like the following
> 
> .\modengine2_launcher.exe -t er -c .\config_eldenring.toml -p "D:\path\to\game\eldenring.exe"
> 
> Obviously, you have to use the correct path to where it's installed in your PC

Works perfectly, thanks for this!

**Comment by vswarte** [comment]
It's not hardcoded, it uses steam to lookup the game's path. Usually when this issue comes around people are playing with a pirated copy which we don't support.

Feel free to reopen the issue if you're playing with a legit steam-bought copy of the game.
