### ISSUE TITLE
Dark Souls 3: Mod Engine 2 fails to load mod changing Data0.bdt

### ISSUE THREAD

**Issue by GuyLivingUnderARock** [soulsmods/ModEngine2#200]
I am having an issue with modding DS3 where the "Very Very Hard Mode" mod which modifies the Data0.bdt file seems to not work when using Mod Engine 2. The mod works when I replace the default Data0.bdt and launch the game through steam, but not when I place the Data0.bdt in Mod Engine 2's mod folder.

I am unsure if I am misusing Mod Engine 2 or if this is an issue, so I thought this would be the best place to ask/mention it.
Many thanks in advance.

Mod: [https://www.nexusmods.com/darksouls3/mods/1575](url)
ME2 DS3 Config File: [config_darksouls3.txt](https://github.com/soulsmods/ModEngine2/files/15217574/config_darksouls3.txt)
ME2 Log: [modengine_2024-05-06.log](https://github.com/soulsmods/ModEngine2/files/15217579/modengine_2024-05-06.log)
ME2 Mod Folder Tree: [ME2ModFolderTree.txt](https://github.com/soulsmods/ModEngine2/files/15217599/ME2ModFolderTree.txt)

Edit: This appears to be the case for all mods that require Mod Manager 2 to load a DataX.bdt file

**Comment by HommeDeGout** [comment]
I have the same problem, did you manage to found a solution ? :D

**Comment by vswarte** [comment]
ME2 doesn't support loading BDTs as a whole, it only deals with loose, extracted, files. It's not in the plans and there's much better ways of distributing mods than shipping a whole Data0.bdt so I doubt this will ever be a feature.
Closing, feel free to reopen if there's other questions on this subject.
