### ISSUE TITLE
Multiple dll mods = Could not find signature!

### ISSUE THREAD

**Issue by pino1536** [soulsmods/ModEngine2#210]
### Test Setup:
- Clean Elden Ring Steam install with DLC
- ModEngine2 directly into Elden Ring dir
```
mod
modengine2
config_eldenring.toml
start_protected_game.exe (= renamed modengine2_launcher.exe)
```
- Testet witch 2 dll mods: UltrawideFix.dll and UnlockTheFps.dll in mod dir.
```
mod\UltrawideFix
mod\UltrawideFix.dll
mod\UnlockTheFps
mod\UnlockTheFps.dll
```
- WITHOUT Elden Mod Loader

### First Test (single dll mod)
Single mod dll enabled in "config_eldenring.toml"
```
external_dlls = [ "mod\\UnlockTheFps.dll" ]
```
= No Problems

### Second Test (two dll mods)
Two dll mods enabled in "config_eldenring.toml"
```
external_dlls = [ "mod\\UnlockTheFps.dll", "mod\\UltrawideFix.dll" ]
or
external_dlls = [ "mod\\UltrawideFix.dll", "mod\\UnlockTheFps.dll" ]
```
= Error: UnlockTheFps: Could not find signature!

My "solution" for now is to use the Elden Mod Loader too but hopefully it helps to resolve the bug :)

**Comment by pino1536** [comment]
Forgot to write... checked the Elden Mod Loader log and both dll mods runns perfect. Must be a ModEngine2 problem so.

**Comment by vswarte** [comment]
This is not an ME2 problem, this is an UnlockTheFps problem.
