### ISSUE TITLE
ICON IN DLC NOT WORKING WITH MODENGINE 2

### ISSUE THREAD

**Issue by DANTELEAS** [soulsmods/ModEngine2#218]
New DLC items now do not load icons for all DLC items if you launch the game through Modengine 2. HOW TO FIX ICONS THANKS. when you launch it not through the mod engine, but directly, the icons work.
![image](https://github.com/soulsmods/ModEngine2/assets/93083846/7efd04a1-9770-40b6-b98c-d61ce9c7cb98)

**Comment by lennylenlen** [comment]
I have the same issue, the lost table of grace icon replaces all graces on map, some spells and incants icons are swapped around, and weapon stat icons are torn or swapped when applying ashes of war

**Comment by DANTELEAS** [comment]
> У меня та же проблема, значок потерянного стола благодати заменяет все благодати на карте, значки некоторых заклинаний и чар поменяны местами, а значки характеристик оружия порваны или поменяны местами при применении пепла войны.
Тоже самое, один в один, пришлось без моденжина играть потому что нет банально значков и магия поменяна местами, как я не старался это исправить, ничего не меняется воовсе и все эти значки новые предметы из ДЛС не показывают, все остальное показывает, только новая карта и ДЛС там значки не работают.

**Comment by DANTELEAS** [comment]
Map for Goblins v1.04-3091-1-04-1719430350 delete this mod It was because of him that the problem was, I advise you to do the same. Problem solved!

**Comment by lennylenlen** [comment]
Thanks, but I don't have that mod. But I did delete the PS5 UI mod and it wroks fine now
