### ISSUE TITLE
Mod Engine 2 is corrupting my progress in Elden Ring

### ISSUE THREAD

**Issue by Caardvlr** [soulsmods/ModEngine2#225]
When i start elden ring in the normal exe the game open normally with my save normally, but when i start with mod engine launcher my save is corrupted, i already make a backup for the save, but have a reason to my save to be corrupted? (Sorry if the text have some pronunciation errors, i am brazilian and i took advantage of this text to test my english.)

**Comment by matthias-sebastos** [comment]
I have the same issue happening to me. Latest version from Steam. It's installed in a different drive however.

**Comment by DigitalMajdur** [comment]
> When i start elden ring in the normal exe the game open normally with my save normally, but when i start with mod engine launcher my save is corrupted, i already make a backup for the save, but have a reason to my save to be corrupted? (Sorry if the text have some pronunciation errors, i am brazilian and i took advantage of this text to test my english.)

u got any solutions for this yet?

**Comment by matthias-sebastos** [comment]
> u got any solutions for this yet?

If you are running a mod in MO2 that hasn't been updated for the current version, then the save file will get corrupted, as the regulation.bin files are different versions.

**Comment by DigitalMajdur** [comment]
The mod is updated for the dlc and I am using the latest 1.12 version game
but for some reason it's still not working and it's not just this one mod
every mod isn't working

**Comment by vswarte** [comment]
This an issue with the regbin checks and the mods you are running, not with ME2. See if any of the mods you're running are stuck on a pre-DLC regbin since it will need updating.
