### ISSUE TITLE
Howto: fix Eldenring [error]10b, crash, couldn't find game, work with seamless coop mod

### ISSUE THREAD

**Issue by 1265775896** [soulsmods/ModEngine2#229]
### 1. run .bat file and crashed
eg: [stderr] [error] Couldn't create process: 10b
eg2: crashed/not opening

**reason**: ModEngine2 are so genius, **EVERYTHING MUST BE UNDER** _"game"_ Directory, anything else won't work, EVEN you use -p to specified game path, especially for pirate version!

**fix**: 
- you **MUST** put every file of the game inside directory named "game", if none, create one.
- also put files of Modengine2 in the same directory
- check you have files such as eldenring.exe, .bat file, modengine2_launcher.exe and etc **MUST BE UNDER** _"game"_
- run .bat again
- if failed, edit .bat file, change content to something like this:
`chcp 65001
:: The above line is necessary in case you edit this file to lead to a path with Unicode characters.
.\modengine2_launcher.exe -t er -c.\config_eldenring.toml -p "D:\Steam\ELDEN RING\game\eldenring.exe"`
- make sure path are exist between the quotations, and **MUST BE UNDER** _"game"_ Directory!!!
- run .bat and enjoy!

### 2. Work with seamless co-op mod
**fix**:
- same problem, everything Modengine2 Detect **MUST BE UNDER** _"game"_ directory
- extract files of seamless co-op "UNDER"  _"game"_ directory, also move files in "SeamlessCoop" directory to _"game"_ directory
- edit config_eldenring.toml
- find and change this line:
- `external_dlls = [ "ersc.dll" ]`
- save and run .bat, enjoy!

### Conclusion
Due to bugs of genius Modengine2, to avoid any unexpected problems, **EVERYTHING MUST BE UNDER** _"game"_ Directory!

**Comment by vswarte** [comment]
None of what you describe is a bug, you are just fumbling to setup a pirated copy because we don't support those. I'd like to ask you to stop tagging other unrelated issues with this shit.

**Comment by 1265775896** [comment]
> None of what you describe is a bug, you are just fumbling to setup a pirated copy because we don't support those. I'd like to ask you to stop tagging other unrelated issues with this shit.

"None of what you describe is a bug"? 
have you ever realized the problem is your shit coding skill?
"Unrelated issues"?
**Which may solve 1/3 issue "Launcher not launching"?** 

And even you never figure it out is because you can't even get the most basic PATH FINDING right??? 
For example, in your _config_eldenring.toml_, you got a example like this:
![image](https://github.com/user-attachments/assets/755866f9-f020-4b66-9ae3-73b3ddd9fd11)
May I ask you to test it yourself? It's NOT works, correct relative path method are using \\\ to seprate, like this:
{ enabled = true, name = "map", path = "mod\\\map" }
[ "SeamlessCoop\\\ersc.dll" ]

Back to the point, I tried with my official steam version at first, and Launcher failed to launch, Finally I changed .bat to use "-p" to point out the path for your shit and works. Then waste my 3 hours to test it out for others that you must have "eldenring.exe" under "game" directory to work! May I ask you what's this logic? not even I pointed with -p? Blame your code, not me. I never saw this happen to any project.

Also don't make me laugh, Are you saying your PIRATE modding tool is not support PIRATE games? Modding tools in some country is even a crime! Others are gray zone. Like famous "Yuzu" project.  You don't have the right to play a moral guardian here. Not mention this issue is not even related to pirate, is your shit code.

As a result, I also placed my method on some forum and successfully helped several people to use your shit, and try tagged other same issue people still wondering to help, which supposed to be your job, there is nothing wrong with me. I played a lot of games with mods launcher, yours are the worst I ever seen. every others are out-of-box and fancy.
 
Now, would you mind ignore my post and get down to fix 1/3 issues that "Launcher not launching" "mods not working"? If so many people got same issue, its your problem. 

Please no more reply, and sorry for anyone who seen this, and hope everyone can enjoy the game!

**Comment by garyttierney** [comment]
```
# Absolute paths to mods are supported but must use '\\' to separate path items. For example, if your mod is at E:\coolstuff\coolmod, you must enter
# the path in the config as "E:\\coolstuff\\coolmod".
```

I think it's a reading comprehension issue, actually
