### ISSUE TITLE
Game doesn't lunch.

### ISSUE THREAD

**Issue by Wolf1030** [soulsmods/ModEngine2#39]
Soooo what should we do if we don't have the game in the steam library? Even sticking it in the game's main folder doesn't work either.

**Comment by garyttierney** [comment]
Place it in the folder containing the game executable (the Game folder inside the installation). The launcher will look for DarkSoulsIII.exe or eldenring.exe

**Comment by Wolf1030** [comment]
Read what I said instead of the title.

**Comment by dalastdragon** [comment]
I think what wolf is asking is if the game lives in c:\games\eldenring What is the syntax to edit the toml file to reflect that. I'm not running the game on steam either and putting the mod files in the game directory doesn't work, should I edit the bat file or the toml file and what would be the proper line to add to get the modengine to see the game, the readme explains how to add several mods in toml file but not how to direct modengine to point to several paths for the game. I even looked for different switches within the executible for modengine...the instruction for the target switch (t) is a bit unclear.

**Comment by disgusdad** [comment]
I am also wondering how to properly use the '-t' option to launch Elden Ring installed to a non-steamapp directory.

**Comment by garyttierney** [comment]
> Read what I said instead of the title.

Read my message again,

**Comment by Wolf1030** [comment]
> > Read what I said instead of the title.
> 
> Read my message again.

obviously I did or else I wouldn't be here asking, let alone give you that information already. Already did, nothing happens. *face palm*

**Comment by garyttierney** [comment]
> What is the syntax to edit the toml file to reflect that. I'm not running the game on steam either and putting the mod files in the game directory doesn't work,

The TOML file doesn't contain game paths, There's currently only 2 mechanisms for finding the game exe (and folder):
- Find a Steam installation with the matching appid
- Find an executable named <game.exe> adjacent to modengine2_launcher.exe

**Comment by Wolf1030** [comment]
> > The TOML file doesn't contain game paths, There's currently only 2 mechanisms for finding the game exe (and folder):
> 
> * Find an executable named <game.exe> adjacent to modengine2_launcher.exe

Sorry to say, but it does not. 
https://puu.sh/ITM7j/c9881f74e3.png
