### ISSUE TITLE
[Elden Ring] mods=[enabled=false..].... doesn't function. Mod(s) loads anyway.

### ISSUE THREAD

**Issue by Xetaxheb** [soulsmods/ModEngine2#41]
Pretty straightforward. enabled=false just... doesn't prevent loading that directory. I imagine it's broken with everything but my obvious test case is \msg\engus\item.msgbnd.dcx

A few examples, \mod\ contains correct msgbnd, \mod2\ contains incorrect msgbnd:

Correct msgbnd: 
    mods = [ { enabled = true, name = "default", path = "mod" }, { enabled = true, name = "yee", path = "mod2" } ]

Correct msgbnd: 
    mods = [ { enabled = true, name = "default", path = "mod" }, { enabled = false, name = "yee", path = "mod2" } ]

Incorrect msgbnd: 
    mods = [ { enabled = true, name = "yee", path = "mod2" }, { enabled = true, name = "default", path = "mod" } ]

Incorrect msgbnd: 
    mods = [ { enabled = false, name = "yee", path = "mod2" }, { enabled = true, name = "default", path = "mod" } ]

**Comment by garyttierney** [comment]
Fixed in https://github.com/soulsmods/ModEngine2/releases/tag/preview4.
