### ISSUE TITLE
Mods not loading for Elden Ring

### ISSUE THREAD

**Issue by LaykaKiro** [soulsmods/ModEngine2#65]
I swear I must be doing something wrong.
I have the mods in the "mod" folder and I'm launching the .bad file and the game isn't loading with mods.

**Comment by ThaSundanceKid** [comment]
Same here, i tried all variants with absolute path in.
Got it working by putting the files from https://www.nexusmods.com/eldenring/mods/117 in mod engine2 folder and use "mods" folder for the mods

**Comment by LaykaKiro** [comment]
All good, I solved my own problem. It turns out that "regulation.bin" effects newly created characters, and not characters that already exist.

**Comment by lKobi** [comment]
> All good, I solved my own problem. It turns out that "regulation.bin" effects newly created characters, and not characters that already exist.

This is false, the issue you having was already covered by FAQ.

**Comment by LaykaKiro** [comment]
> > All good, I solved my own problem. It turns out that "regulation.bin" effects newly created characters, and not characters that already exist.
> 
> This is false, you cannot use old regulation.bin files (the game will revert the changes), as for using the the MODs on an older save, you need to load the save with the newer regulation (vanilla) before replacing it.

Well when I tried that it didn't work. Unless I truly did just do it wrong.

**Comment by lKobi** [comment]
When the game updates, removed all the MODs you have (trigger a steam file check if you have to) and load your save normally, let it trigger a save (teleport to a site of grace).

Then you can re-apply the MODs (which need to be updated for the newer version). If you use an outdated regulation.bin the game will simply ignore it.

You do not need a new save to apply MODs.

**Comment by LaykaKiro** [comment]
> When the game updates, remove all the MODs you have (trigger a steam file check if you have to) and load your save normally, let it trigger a save (teleport to a site of grace).
> 
> Then you can re-apply the MODs (which need to be updated for the newer version). If you use an outdated regulation.bin the game will simply ignore it.
> 
> You do not need a new save to apply MODs, and do not rely on Mod Engine to replace the regulation.bin (is extremely unreliable), do it yourself manually as intended.

Okay, I'll take a note of that. May I ask how to have the modded Regulation.bin apply to current saves? Because when I boot up a save, it's unaltered. Do I have to travel to a Site of Grace?

**Comment by ThaSundanceKid** [comment]
I just cant get this to work at all
tried all variants on the "skipintro" for example
How would you specify the config_eldenring.toml: 
```
mods = [
    { enabled = true, name = "SkipTheIntro.dll", path = "I:\\SteamLibrary\\steamapps\\common\\ELDEN RING\\ModEngine-2.0.0-preview3-win64\\mod\\SkipTheIntro" }
]
```

**Comment by lKobi** [comment]
> > When the game updates, remove all the MODs you have (trigger a steam file check if you have to) and load your save normally, let it trigger a save (teleport to a site of grace).
> > Then you can re-apply the MODs (which need to be updated for the newer version). If you use an outdated regulation.bin the game will simply ignore it.
> > You do not need a new save to apply MODs, and do not rely on Mod Engine to replace the regulation.bin (is extremely unreliable), do it yourself manually as intended.
> 
> Okay, I'll take a note of that. May I ask how to have the modded Regulation.bin apply to current saves? Because when I boot up a save, it's unaltered. Do I have to travel to a Site of Grace?

I wouldn't know how to answer that besides what I already told you, changes to Regulation.bin affect all my saves (both old and new).

Just don't rely on Mod Engine 2 to replace Regulation.bin, do it yourself on the game folder and you'll avoid most issues.

> I just cant get this to work at all tried all variants on the "skipintro" for example How would you specify the config_eldenring.toml:
> 
> ```
> mods = [
>     { enabled = true, name = "SkipTheIntro.dll", path = "I:\\SteamLibrary\\steamapps\\common\\ELDEN RING\\ModEngine-2.0.0-preview3-win64\\mod\\SkipTheIntro" }
> ]
> ```

Known issue with Mod Engine 2, do not rely on it for stuff like that, use https://www.nexusmods.com/eldenring/mods/117 to load libraries.

**Comment by idkwhy635** [comment]
it wont work at all idk
