### ISSUE TITLE
The system disk is not C cant call dinput8.dll

### ISSUE THREAD

**Issue by PilotSherlock** [soulsmods/ModEngine2#69]
My system disk is not C,so this ModEngine cant call dinput8.dll,i copy a dinput8.dll from system disk to C,it no longer returns error,but ModEngine still not work,maybe need change the absolute path

**Comment by garyttierney** [comment]
Fixed in https://github.com/soulsmods/ModEngine2/commit/8c1eb210756ecca71d2d46ae94eade8899dd9558 for the next release.

**Comment by garyttierney** [comment]
Fixed in preview4.
