### ISSUE TITLE
Modengine2 with DarkSouls3 1.15.1 patch

### ISSUE THREAD

**Issue by Mosaic-pixel** [soulsmods/ModEngine2#78]
Hi.
Situation is as follows - after DarkSouls3 1.15.1 patch Modengine2 does not work. Game crashes after finishing character creation and loading map. Issue seems to be present where HoodiePatcher is involved with big mods like Cinders or Hollow Overhaul.

What would be correct syntax to chain such .dll files?
Thanks!

**Comment by garyttierney** [comment]
Mod Engine 2 has been updated to work on the latest patch in https://github.com/soulsmods/ModEngine2/releases/tag/preview4. If you're still crashing with other mods on this update then you'll need to ask those mod authors to update their code.
